### ISSUE TITLE
University websites category in Top Hacker News Submissions by Category

### ISSUE THREAD

**Issue by PatMyron** [antontarasenko/smq#5]
https://github.com/antontarasenko/smq/blob/master/reports/hackernews-top-submissions-by-category.md#L50

seems to be matching on the `edu` substring which has some false positives:

http://eduardo.intermeta.com.br/this-is-how-visa-works
http://www.theguardian.com/commentisfree/2013/aug/19/david-miranda-schedule7-danger-reporters

**Comment by antontarasenko** [comment]
@PatMyron Spotted! I should've search by the ".edu" string. The irrelevant links removed. Thank you!
